function [Ux, Uy, Vx, Vy] = UVMatrixConstruction(N)

Ux = spdiags(-1.*ones(N.*N,1),0,N.*N,N.*N) + spdiags(ones(N.*N,1),1,...
    N.*N,N.*N);
Uy = spdiags(-1.*ones(N.*N,1),0,N.*N,N.*N) + spdiags(ones(N.*N,1),N,...
    N.*N,N.*N);

Vx = spdiags(1.*ones(N.*N,1),0,N.*N,N.*N) + spdiags(-1.*ones(N.*N,1),-1,...
    N.*N,N.*N);

Vy = spdiags(1.*ones(N.*N,1),0,N.*N,N.*N) + spdiags(-1.*ones(N.*N,1),-N,...
    N.*N,N.*N);